In [9]:
import sqlite3
import pandas as pd

# DB 생성 및 연결

In [10]:
# SQLite 데이터베이스 파일 생성
conn = sqlite3.connect('ASAC_MAP.db')
cursor = conn.cursor()

In [3]:
# csv to sqlite 변환 함수

def csv_to_sqlite(csv_file, db_file, table_name, chunk_size=1000):
    try:
        # SQLite 데이터베이스 파일 연결
        conn = sqlite3.connect(db_file)
        
        # CSV 파일을 청크 단위로 읽어 SQLite로 변환
        for chunk in pd.read_csv(csv_file, chunksize=chunk_size):  # 여기에서 괄호 ()를 반드시 사용해야 합니다.
            chunk.to_sql(table_name, conn, if_exists='replace', index=False)
        
        # 변경 사항 저장
        conn.commit()
        print(f"CSV 파일을 SQLite 데이터베이스 '{table_name}' 테이블로 변환 완료")
    
    except Exception as e:
        print(f"오류 발생: {e}")
    
    finally:
        # 연결 종료
        conn.close()


# # 함수 사용 예시
# csv_to_sqlite('your_data.csv', 'mydatabase.db', 'review')

## Review table

In [11]:
reveiw_csv = f'csv/final_datasets.csv'

In [12]:
# reveiw table 추가
csv_to_sqlite(reveiw_csv, 'ASAC_MAP.db', 'review')

CSV 파일을 SQLite 데이터베이스 'review' 테이블로 변환 완료

## Business table

In [75]:
dusiness_csv = pd.read_csv('csv/sample_business_final.csv')

In [76]:
dusiness_csv.head()

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,is_open,attributes,category,region,review_count_biz,average_stars_biz,bined_stars,review_count_bin
0,13368,110650,M Restaurant,231 S 8th St,Philadelphia,PA,19106,39.947326,-75.154311,0,NaN,"['Food', 'Desserts']","Philadelphia, 19106",51.0,3.705882,3.5,"(45.0, 65.0]"
1,17740,110907,Baker Boss Cafe,5694 Nolensville Pike,Nashville,TN,37211,36.046953,-86.710437,1,NaN,"['Restaurants', 'Vietnamese']","Nashville, 37211",59.0,4.406780,4.5,"(45.0, 65.0]"
2,2010,28638,Embassy Suites by Hilton Tampa Downtown Conven...,513 S Florida Ave,Tampa,FL,33602,27.942315,-82.454761,1,NaN,"['Restaurants', 'Cafes']","Tampa, 33602",108.0,2.212963,2.0,"(105.0, 125.0]"
3,51937,100086,Chili's,1741 Manhattan Blvd,Harvey,LA,70058,29.888604,-90.055884,1,NaN,"['Restaurants', 'American (Traditional)']","Harvey, 70058",88.0,1.863636,2.0,"(85.0, 105.0]"
4,10484,136473,The Blind Tiger Cafe - Westchase,10118 Montague St,Tampa,FL,33626,28.044055,-82.597213,1,NaN,"['Restaurants', 'Sandwiches']","Tampa, 33626",99.0,3.787879,4.0,"(85.0, 105.0]"

In [77]:
dusiness_csv = dusiness_csv.drop(columns=['Unnamed: 0'])

In [78]:
dusiness_csv = f'csv/sample_business_final.csv'

In [84]:
csv_to_sqlite(dusiness_csv, 'ASAC_MAP.db', 'business')

CSV 파일을 SQLite 데이터베이스 'business' 테이블로 변환 완료

## User table

In [85]:
user_csv = f'csv/sample_user_df.csv'

In [98]:
user_df=pd.read_csv('csv/sample_user_df.csv')
user_df.head()

C:\Users\NT551XCJ\AppData\Local\Temp\ipykernel_1252\3580035048.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  user_df=pd.read_csv('csv/sample_user_df.csv')

,user_id,name,yelping_since,useful,funny,cool,elite,friends,fans,compliment_hot,...,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,review_count_user,average_stars_user,most_visited_region,visit_cnt
0,1693126,Walker,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,250,...,232,844,467,467,239,180,3.0,3.666667,NaN,NaN
1,1461918,Daniel,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,1145,...,1847,7054,3131,3131,1521,1946,21.0,3.904762,NaN,NaN
2,109832,Steph,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,89,...,66,96,119,119,35,18,0.0,NaN,NaN,NaN
3,919911,Gwen,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,24,...,12,16,26,26,10,9,0.0,NaN,NaN,NaN
4,1404382,Karen,2007-01-05 19:40:59,29,15,7,NaN,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,1,...,1,1,0,0,0,0,7.0,3.428571,NaN,NaN

In [86]:
csv_to_sqlite(user_csv, 'ASAC_MAP.db', 'user')

CSV 파일을 SQLite 데이터베이스 'user' 테이블로 변환 완료

## table 조회

In [13]:
import sqlite3

# 데이터베이스 파일에 연결
conn = sqlite3.connect('ASAC_MAP.db')
cursor = conn.cursor()

# 테이블 조회 쿼리 실행
cursor.execute("SELECT * FROM business LIMIT 10")

# 결과를 가져옴
rows = cursor.fetchall()

# 결과 출력
for row in rows:
    print(row)

(13368, 110650, 'M Restaurant', '231 S 8th St', 'Philadelphia', 'PA', '19106', 39.9473257341, -75.1543113996, 0, None, "['Food', 'Desserts']", 'Philadelphia, 19106', 51.0, 3.7058823529411766, 3.5, '(45.0, 65.0]')
(17740, 110907, 'Baker Boss Cafe', '5694 Nolensville Pike', 'Nashville', 'TN', '37211', 36.0469533703, -86.7104372755, 1, None, "['Restaurants', 'Vietnamese']", 'Nashville, 37211', 59.0, 4.406779661016949, 4.5, '(45.0, 65.0]')
(2010, 28638, 'Embassy Suites by Hilton Tampa Downtown Convention Center', '513 S Florida Ave', 'Tampa', 'FL', '33602', 27.9423153, -82.4547605, 1, None, "['Restaurants', 'Cafes']", 'Tampa, 33602', 108.0, 2.212962962962963, 2.0, '(105.0, 125.0]')
(51937, 100086, "Chili's", '1741 Manhattan Blvd', 'Harvey', 'LA', '70058', 29.8886043, -90.0558844, 1, None, "['Restaurants', 'American (Traditional)']", 'Harvey, 70058', 88.0, 1.8636363636363635, 2.0, '(85.0, 105.0]')
(10484, 136473, 'The Blind Tiger Cafe - Westchase', '10118 Montague St', 'Tampa', 'FL', '33626', 28.0440549, -82.597213, 1, None, "['Restaurants', 'Sandwiches']", 'Tampa, 33626', 99.0, 3.787878787878788, 4.0, '(85.0, 105.0]')
(30202, 87483, 'Sonic Drive-In', '3655 N Mount Juliet Rd', 'Mount Juliet', 'TN', '37122', 36.2213793, -86.5145423, 1, None, "['Food', 'Ice Cream & Frozen Yogurt']", 'Mount Juliet, 37122', 34.0, 1.1764705882352942, 1.0, '(25.0, 45.0]')
(9628, 40372, 'The Breakfast Grille', '8536 Ridge Rd', 'New Port Richey', 'FL', '34654', 28.2797993, -82.6734224, 1, None, "['Restaurants', 'Mediterranean']", 'New Port Richey, 34654', 32.0, 4.09375, 4.0, '(25.0, 45.0]')
(19833, 25856, 'Chapala Mexican Restaurant', '5697 N Glenwood St', 'Garden City', 'ID', '83714', 43.6568282, -116.2801126, 0, None, "['Restaurants', 'Mexican']", 'Garden City, 83714', 29.0, 3.0689655172413794, 3.0, '(25.0, 45.0]')
(60613, 123142, 'Pomodoro Pizza & Italian Restaurant', '200 Chestnut St', 'Downingtown', 'PA', '19335', 40.0076775, -75.6956453, 1, None, "['Restaurants', 'Pizza']", 'Downingtown, 19335', 150.0, 4.42, 4.5, '(145.0, 165.0]')
(1370, 40347, 'Nicoletto’s Italian Kitchen', '2123 Belcourt Ave', 'Nashville', 'TN', '37212', 36.1368318853, -86.8029680469, 1, None, "['Restaurants', 'Italian']", 'Nashville, 37212', 37.0, 4.216216216216216, 4.0, '(25.0, 45.0]')

In [15]:
import sqlite3

# 데이터베이스 파일에 연결
conn = sqlite3.connect('ASAC_MAP.db')
cursor = conn.cursor()

# 테이블 조회 쿼리 실행
cursor.execute("SELECT * FROM review LIMIT 10")

# 결과를 가져옴
rows = cursor.fetchall()

# 결과 출력
for row in rows:
    print(row)

(2600611, 1753161, 95720, 89087, 5.0, 2, 0, 0, 'I was very pleased with how Little Cairo was set up: most customers were seated outside.  That left me half of the dining room.   I placed my order and they invited me to sit anywhere.  Table service very fast.  My Gyro was amazing with a great big salad!! Very healthy lunch, just what I was looking for.  Will be back absolutely! Five stars!', '2020-08-13 19:51:49', "['I was very pleased with how Little Cairo was set up: most customers were seated outside.', 'That left me half of the dining room.', 'I placed my order and they invited me to sit anywhere.', 'Table service very fast.', 'My Gyro was amazing with a great big salad!!', 'Very healthy lunch, just what I was looking for.', 'Will be back absolutely!', 'Five stars!']", 8, "['little cairo', 'half dining', 'placed order', 'table service', 'gyro amazing', 'healthy lunch', 'absolutely', 'stars']", "['little cairo', 'half dining', 'placed order', 'table service', 'gyro amazing', 'healthy lunch', 'absolutely', 'stars']", 0.67718817125, "{'food': ['healthy lunch', 'gyro amazing'], 'service': ['placed order', 'table service'], 'atmosphere': ['little cairo'], 'others': ['absolutely', 'stars', 'half dining']}", "['atmosphere', 'others', 'service', 'service', 'food', 'food', 'others', 'others']", 1, 1, 1, 0, 0, 1, '[0.9752352, -0.16262668, 0.30393854, 0.6958609, 0.99006486, 0.96720636, 0.90964055, 0.73818564]', "{'others': ['gyro fries', 'food gyros', 'food gyro', 'mediterranean cuisine', 'cuisine mediterranean'], 'food': ['gyro fries', 'food gyros', 'food gyro', 'mediterranean cuisine', 'cuisine mediterranean'], 'atmosphere': ['gyro fries', 'fries seasoned', 'fries fries', 'food gyros', 'fries frozen'], 'service': ['gyro fries', 'fries excellent', 'fries mediocre', 'fries great', 'fries seasoned'], 'facility': ['food authentic', 'restaurant', 'order food', 'food critic', 'tasty food'], 'price': ['good food', 'great food', 'food great', 'prices good', 'seating prices']}", 0.5464071894502618, 0.5036075454731542, 0.5190724279717867, 0.6666468573333334, 0.4968736129444445, 0.2538657065517241)
(2600648, 520201, 347827, 126495, 5.0, 1, 0, 0, "So I'm Writing this about pick-up as we did not actually eat there - these are Covid times so -   That being said the burgers were awesome!   We ordered the 1/2 lb build your own burger - all come with lettuce tomato onions and pickle and served with fresh kettle chips - I added cheddar and jalapeño on mine and hubby had blue cheese and mushrooms - hand pattied angus beef served fresh and hot on a bun - that's all no butter or other stuff because real beef doesn't need it.  We have had many many burgers in St Pete and this one is the real deal.", '2021-03-23 01:24:33', '["So I\'m Writing this about pick-up as we did not actually eat there - these are Covid times so -   That being said the burgers were awesome!", "We ordered the 1/2 lb build your own burger - all come with lettuce tomato onions and pickle and served with fresh kettle chips - I added cheddar and jalapeño on mine and hubby had blue cheese and mushrooms - hand pattied angus beef served fresh and hot on a bun - that\'s all no butter or other stuff because real beef doesn\'t need it.", \'We have had many many burgers in St Pete and this one is the real deal.\']', 3, "['burgers awesome', 'build burger', 'burgers st']", "['burgers awesome', 'build burger', 'burgers st']", 0.6574194666666667, "{'food': ['burgers awesome', 'build burger'], 'others': ['burgers st']}", "['food', 'food', 'others']", 1, 0, 0, 0, 0, 1, '[0.8450121, 0.2791373, 0.848109]', "{'others': ['kozuba distillery', 'tacos party', 'friendly restaurants', 'diner tzatziki', 'tacos great'], 'food': ['kozuba distillery', 'tacos party', 'friendly restaurants', 'diner tzatziki', 'tacos great'], 'service': ['turkey burger', 'menu restaurant', 'friendly restaurants', 'eaten restaurant', 'restaurant loved'], 'atmosphere': ['turkey burger', 'friendly restaurants', 'favorite restaurant', 'restaurants sauce', 'place restaurants'], 'facility': ['turkey burger', 'menu restaurant', 'place restaurants', 'restaurant reply', 'turkey sweet'], 'price': ['burgers greek', 'menu restaurant', 'greek tacos', 'restaurant', 'family burgers']}", 0.2760456632669174, 0.3501187992912398, 0.3775664210684489, 0.1758409942571429, 0.469314850590786, 0.0917406248287037)
(2600675, 4832089, 829052, 134035, 5.0, 2, 0, 0, "WOW - so psyched to have this new addition to the philly scene. Been here twice, and both times was blown away by the *incredible* food, friendly service, and interesting wines. The menu changes a lot but I've had a decent number of things so I'll talk about my favorites.   Favorite small plates are the burrata with incredible high quality olive oil and poached tomatoes, fresh and delicious kale Caesar, and the charcoal grilled shrimp. The grilled sourdough was also delicious - but thats a tough thing to mess up. The most surprising dish to me was the sesame asparagus salad. I could have had three of them!   As far as pizza, the sausage and onion was fantastic. These aren't typically toppings I enjoy, but all the ingredients were so great I couldn't get enough. The plain cheese (my normal) was also incredible. I dont think you can go wrong here with the food!  The wine list changes constantly so probably not worth saying what I got, but I ordered a glass of dark rose (????) at the server's suggestion and it was the best wine I've had in a minute! And I'm not even a rose person!   Lastly, the servers are so kind. GO TO SALLY!", '2021-06-30 03:26:39', '[\'WOW - so psyched to have this new addition to the philly scene.\', \'Been here twice, and both times was blown away by the *incredible* food, friendly service, and interesting wines.\', "The menu changes a lot but I\'ve had a decent number of things", "so I\'ll talk about my favorites.", \'Favorite small plates are the burrata with incredible high quality olive oil and poached tomatoes, fresh and delicious kale Caesar, and the charcoal grilled shrimp.\', \'The grilled sourdough was also delicious - but thats a tough thing to mess up.\', \'The most surprising dish to me was the sesame asparagus salad.\', \'I could have had three of them!\', \'As far as pizza, the sausage and onion was fantastic.\', "These aren\'t typically toppings I enjoy, but all the ingredients were so great I couldn\'t get enough.", \'The plain cheese (my normal) was also incredible.\', \'I dont think you can go wrong here with the food!\', \'The wine list changes constantly so probably not worth saying what I got, but I ordered a glass of dark rose (????)\', "at the server\'s suggestion and it was the best wine I\'ve had in a minute!", "And I\'m not even a rose person!", \'Lastly, the servers are so kind.\', \'GO TO SALLY!\']', 17, "['philly scene', 'interesting wines', 'menu changes', 'talk favorites', 'plates burrata', 'grilled sourdough', 'sesame asparagus', 'three', 'pizza sausage', 'toppings enjoy', 'plain cheese', 'wrong food', 'wine list', 'best wine', 'rose person', 'lastly servers', 'sally']", "['philly scene', 'interesting wines', 'menu changes', 'talk favorites', 'plates burrata', 'grilled sourdough', 'sesame asparagus', 'three', 'pizza sausage', 'toppings enjoy', 'plain cheese', 'wrong food', 'wine list', 'best wine', 'rose person', 'lastly servers', 'sally']", 0.6827224887058824, "{'food': ['grilled sourdough', 'pizza sausage', 'toppings enjoy', 'sesame asparagus', 'plates burrata', 'plain cheese'], 'others': ['philly scene', 'sally', 'wrong food', 'interesting wines', 'wine list', 'menu changes', 'best wine', 'rose person', 'talk favorites', 'lastly servers']}", "['others', 'others', 'others', 'others', 'food', 'food', 'food', 'food', 'food', 'food', 'food', 'others', 'others', 'others', 'others', 'others', 'others']", 1, 0, 0, 0, 0, 1, '[0.9897258, 0.98675615, 0.40825936, 0.41050243, 0.96431845, 0.79769504, 0.87381434, 0.74088293, 0.94518965, 0.98397994, 0.95091814, 0.69640607, 0.048569158, 0.9834831, -0.55350655, 0.9467489, 0.4325394]', "{'food': ['pizza options', 'philly pizza', 'pizza delicious', 'pizza fantastic', 'delicious pizza'], 'others': ['philly pizza', 'pizza delicious', 'pizza fantastic', 'delicious pizza', 'pizza tables'], 'atmosphere': ['nyc reservations', 'restaurant philly', 'challenging reservation', 'restaurant', 'cute restaurant'], 'facility': ['nyc reservations', 'pizza fantastic', 'challenging reservation', 'reservations try', 'pizza spot'], 'service': ['challenging reservation', 'reservation random', 'sally guests', 'jumped reservation', 'restaurant philly'], 'price': ['sally pizza', 'pizza good', 'evening pizzazz', 'pizzazz pizza', 'pizza']}", 0.5088152432200003, 0.5906463025618371, 0.59470842556701, 0.1903889749130434, 0.5528002421222229, 0.4921301391)
(2600707, 5431300, 1281767, 20827, 5.0, 1, 2, 0, 'We love this place. They have lots of hard to find cooking ingredients, great selection of ready to heat meals and sfogliatelle!', '2021-02-27 22:59:36', "['We love this place.', 'They have lots of hard to find cooking ingredients, great selection of ready to heat meals and sfogliatelle!']", 2, "['love place', 'meals sfogliatelle']", "['love place', 'meals sfogliatelle']", 0.968078555, "{'food': ['meals sfogliatelle'], 'others': ['love place']}", "['others', 'food']", 1, 0, 0, 0, 0, 1, '[0.98057187, 0.95558524]', "{'others': ['foods altomontes', 'altomonte cheeses', 'altomonte offerings', 'altomontes makes', 'shop altomonte'], 'price': ['authentic lunches', 'altomontes', 'works altomonte', 'patronized altomontes', 'lunches great'], 'food': ['foods altomontes', 'altomonte cheeses', 'altomonte offerings', 'helpful altomonte', 'altomontes makes'], 'atmosphere': ['authentic lunches', 'italian market', 'food market', 'product italy', 'place altomonte'], 'facility': ['altomonte serves', 'altomontes', 'patronized altomontes', 'altomonte', 'italian deliciousness'], 'service': ['shopping experience', 'shop regularly', 'italian delicacies', 'specialty shop', 'unique shopping']}", -0.0463425543488371, 0.1900428650970148, 0.2064255632562187, 0.178390776253731, 0.4069152394545454, 0.1651800992666667)
(2600841, 2428303, 1529142, 86976, 5.0, 0, 0, 0, "Cannot beat this sandwich!  If you haven't been yet, GO!  I like mine extra juicy with broccoli rabe and horseradish.  Grab a drink and stuff your face.  Grab plenty of napkins.", '2019-12-13 22:52:37', '[\'Cannot beat this sandwich!\', "If you haven\'t been yet, GO!", \'I like mine extra juicy with broccoli rabe and horseradish.\', \'Grab a drink and stuff your face.\', \'Grab plenty of napkins.\']', 5, "['beat sandwich', 'haven', 'juicy broccoli', 'drink stuff', 'plenty napkins']", "['beat sandwich', 'haven', 'juicy broccoli', 'drink stuff', 'plenty napkins']", 0.252112106, "{'food': ['juicy broccoli', 'drink stuff', 'beat sandwich'], 'others': ['haven', 'plenty napkins']}", "['food', 'others', 'food', 'food', 'others']", 1, 0, 0, 0, 0, 1, '[0.5964006, 0.3748253, 0.79436386, -0.6598438, 0.15481457]', "{'service': ['sandwiches gravy', 'food served', 'sandwiches delightfully', 'served sandwiches', 'restaurant'], 'food': ['sandwiches gravy', 'food served', 'sandwiches delightfully', 'served sandwiches', 'napkins sandwichs'], 'atmosphere': ['sandwiches gravy', 'food served', 'sandwiches delightfully', 'restaurant', 'offer sandwiches'], 'others': ['sandwiches gravy', 'food served', 'sandwiches delightfully', 'served sandwiches', 'beefy savory'], 'price': ['amazing bartender', 'favorite philly', 'delicious beef', 'beef gravy', 'philly peeps'], 'facility': ['roast beef', 'beef sandwich', 'ordered roast', 'best roast', 'roast']}", 0.4120731754327732, 0.4245637964553576, 0.4181978462907221, 0.5659314641081082, 0.3074357859032258, 0.3041437297959184)
(2600963, 5693491, 421423, 6695, 5.0, 0, 0, 0, "Food was excellent! Service was excellent as well. Blackened shrimp Po'boy was a nice choice. We will be back!!!", '2019-07-25 16:28:18', '[\'Food was excellent!\', \'Service was excellent as well.\', "Blackened shrimp Po\'boy was a nice choice.", \'We will be back!!!\']', 4, "['food excellent', 'service excellent', 'blackened shrimp', 'back']", "['food excellent', 'service excellent', 'blackened shrimp', 'back']", 0.946843785, "{'food': ['blackened shrimp'], 'service': ['service excellent'], 'others': ['food excellent']}", "['others', 'service', 'food', 'others']", 1, 1, 0, 0, 0, 1, '[0.9779162, 0.955153, 0.93997014, 0.9143358]', "{'food': ['food served', 'food place', 'restaurant great', 'service delicious', 'food friendly'], 'service': ['local food', 'food served', 'beer restaurant', 'bar food', 'restaurants'], 'atmosphere': ['bar friendly', 'bar food', 'fun bar', 'restaurant bar', 'hang drinks'], 'others': ['friendly bartender', 'restaurant great', 'restaurant good', 'dining restaurants', 'bar restaurant'], 'facility': ['drinks food', 'restaurant good', 'bar restaurant', 'fun bar', 'restaurant bar'], 'price': ['shrimp appetizer', 'shrimp presented', 'shrimp', 'boom shrimp', 'shrimp cocktail']}", 0.363562733469799, 0.3859937792137205, 0.4044911073388431, 0.3058977947234041, 0.3355182997510731, 0.4082409042272726)
(2601113, 5043511, 432452, 22138, 3.0, 1, 0, 0, 'It was kind of hard figuring what rating to give because the coffee I got would be a 4 and the food 1 or zero.  Atmosphere: very calm, clean, and aesthetically appealing.  A nice place to do work on a Sunday   Coffee: I ordered a maple cardamom latte which was really delicious.  I love sweetened coffee and this had the right amount of flavor where I didnt need to add anything.  Food: Dissapointing and nothing special to be honest in my opinion. Small and the biscuit was rather tough.  The bacon was nonexistent and  just not worth the money. I would have rather made it myself or go to a different place for food.   If I return, this would definately just be a coffee/work environment for me', '2018-12-09 16:42:51', "['It was kind of hard figuring what rating to give because the coffee I got would be a 4 and the food 1 or zero.', 'Atmosphere: very calm, clean, and aesthetically appealing.', 'A nice place to do work on a Sunday   Coffee: I ordered a maple cardamom latte which was really delicious.', 'I love sweetened coffee and this had the right amount of flavor where I didnt need to add anything.', 'Food: Dissapointing and nothing special to be honest in my opinion.', 'Small and the biscuit was rather tough.', 'The bacon was nonexistent and  just not worth the money.', 'I would have rather made it myself or go to a different place for food.', 'If I return, this would definately just be a coffee/work environment for me']", 9, "['rating coffee', 'atmosphere calm', 'sunday coffee', 'sweetened coffee', 'food dissapointing', 'small biscuit', 'bacon nonexistent', 'place food', 'coffee work']", "['rating coffee', 'atmosphere calm', 'sunday coffee', 'sweetened coffee', 'food dissapointing', 'small biscuit', 'bacon nonexistent', 'place food', 'coffee work']", 0.0909090499999999, "{'food': ['small biscuit', 'bacon nonexistent'], 'atmosphere': ['atmosphere calm'], 'others': ['food dissapointing', 'sunday coffee', 'place food', 'coffee work', 'rating coffee', 'sweetened coffee']}", "['others', 'atmosphere', 'others', 'others', 'others', 'food', 'food', 'others', 'others']", 1, 0, 1, 0, 0, 1, '[-0.5730015, 0.9442648, 0.9847781, 0.9713928, -0.9264267, 0.15912987, -0.9094072, -0.21764119, 0.38509247]', "{'atmosphere': ['appealing coffee', 'coffee coma', 'coffee phenomenal', 'coffee friendly', 'nearby coffee'], 'others': ['nearby coffee', 'looking coffeehouse', 'coffee visit', 'visit coffee', 'appealing coffee'], 'food': ['enjoy coffee', 'enjoyed coffees', 'coffee visit', 'enjoying coffee', 'visit coffee'], 'facility': ['coma coffee', 'appealing coffee', 'coffee yelp', 'experienced coffee', 'mediocre coffee'], 'service': ['appealing coffee', 'experience coffee', 'coffee yelp', 'coffee friendly', 'visit coffee'], 'price': ['lattes family', 'fancy latte', 'flavors lattes', 'speciality lattes', 'lattes']}", 0.2833141086018865, 0.4014362788960575, 0.4090821653939395, 0.3039968301284402, 0.3847628789714287, 0.362304026359694)
(2601238, 1314652, 78246, 6695, 4.0, 0, 0, 0, 'This pub had great food! I got the Ruben, 2 others got the fish and chips. All were amazing! A bit Smokey and definitely a dive, but the food was worth it and no wait if you eat at "normal dinner hours"', '2021-07-04 00:12:37', '[\'This pub had great food!\', \'I got the Ruben, 2 others got the fish and chips.\', \'All were amazing!\', \'A bit Smokey and definitely a dive, but the food was worth it and no wait if you eat at "normal dinner hours"\']', 4, "['pub great', 'ruben got', 'amazing', 'dive food']", "['pub great', 'ruben got', 'amazing', 'dive food']", 0.70977371, "{'food': ['amazing', 'dive food'], 'others': ['ruben got', 'pub great']}", "['others', 'others', 'food', 'food']", 1, 0, 0, 0, 0, 1, '[0.9787195, 0.08701594, 0.9834522, 0.7899072]', "{'food': ['food served', 'food place', 'restaurant great', 'service delicious', 'food friendly'], 'service': ['local food', 'food served', 'beer restaurant', 'bar food', 'restaurants'], 'atmosphere': ['bar friendly', 'bar food', 'fun bar', 'restaurant bar', 'hang drinks'], 'others': ['friendly bartender', 'restaurant great', 'restaurant good', 'dining restaurants', 'bar restaurant'], 'facility': ['drinks food', 'restaurant good', 'bar restaurant', 'fun bar', 'restaurant bar'], 'price': ['shrimp appetizer', 'shrimp presented', 'shrimp', 'boom shrimp', 'shrimp cocktail']}", 0.363562733469799, 0.3859937792137205, 0.4044911073388431, 0.3058977947234041, 0.3355182997510731, 0.4082409042272726)
(2601287, 5613687, 389982, 22138, 5.0, 0, 0, 0, 'My favorite coffee shop! I love the ever changing bakery display of goods. The breakfast sandwich is my favorite thing to get and my favorite drink has to be either the salted caramel cold foam cold brew or the pink lady latte! I like to do my homework here during the week and bring friends during the weekend!', '2021-09-13 18:16:59', "['My favorite coffee shop!', 'I love the ever changing bakery display of goods.', 'The breakfast sandwich is my favorite thing to get and my favorite drink has to be either the salted caramel cold foam cold brew or the pink lady latte!', 'I like to do my homework here during the week and bring friends during the weekend!']", 4, "['coffee shop', 'bakery display', 'breakfast sandwich', 'homework week']", "['coffee shop', 'bakery display', 'breakfast sandwich', 'homework week']", 0.918732705, "{'food': ['breakfast sandwich', 'bakery display'], 'others': ['coffee shop', 'homework week']}", "['others', 'food', 'food', 'others']", 1, 0, 0, 0, 0, 1, '[0.98236656, 0.98297805, 0.98687536, 0.72271085]', "{'atmosphere': ['appealing coffee', 'coffee coma', 'coffee phenomenal', 'coffee friendly', 'nearby coffee'], 'others': ['nearby coffee', 'looking coffeehouse', 'coffee visit', 'visit coffee', 'appealing coffee'], 'food': ['enjoy coffee', 'enjoyed coffees', 'coffee visit', 'enjoying coffee', 'visit coffee'], 'facility': ['coma coffee', 'appealing coffee', 'coffee yelp', 'experienced coffee', 'mediocre coffee'], 'service': ['appealing coffee', 'experience coffee', 'coffee yelp', 'coffee friendly', 'visit coffee'], 'price': ['lattes family', 'fancy latte', 'flavors lattes', 'speciality lattes', 'lattes']}", 0.2833141086018865, 0.4014362788960575, 0.4090821653939395, 0.3039968301284402, 0.3847628789714287, 0.362304026359694)

In [14]:
# 모든 테이블 이름 조회
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

# 테이블 이름 출력
for table in tables:
    print(table[0])

business
user
review

In [20]:
import sqlite3
import pandas as pd

# 데이터베이스 파일 경로 지정
database_path = 'ASAC_MAP.db'

# 데이터베이스 연결
conn = sqlite3.connect(database_path)

# 쿼리 실행
biz_id = 110907
query = "SELECT * FROM review WHERE business_id = {biz_id};"
df = pd.read_sql_query(query, conn)

# 결과 출력
print(df)

# 데이터베이스 연결 종료
conn.close()

Empty DataFrame
Columns: [index, review_id, user_id, business_id, stars, useful, funny, cool, text, date, sentences, sentence_counts, keywords_ug, keywords_bg, compound_score_mean, topics_raw, topics, food, service, atmosphere, facility, price, others, compound_score, keyword_last, service_score, others_score, food_score, price_score, atmosphere_score, facility_score]
Index: []

[0 rows x 31 columns]

In [92]:
# 연결 종료
conn.close()

테이블 삭제

In [7]:
import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('ASAC-MAP.db')
cursor = conn.cursor()

# SQL command to drop the review table
drop_table_command = "DROP TABLE IF EXISTS review;"

try:
    cursor.execute(drop_table_command)
    conn.commit()  # Commit the changes to the database
    print("Review table has been deleted successfully.")
except sqlite3.Error as e:
    print(f"An error occurred: {e}")

finally:
    # Close the cursor and connection to SQLite
    cursor.close()
    conn.close()

Review table has been deleted successfully.